### ISSUE TITLE
too many arguments to function

### ISSUE THREAD

**Issue by privategrim** [brumster/EDTracker2#12]
Hi, I got this error when I try to uploading the calibration sketch. How I fix this? I'm prretty sure that I follow the instructions correctly.

**mpu_set_accel_bias_6050_reg(aBias, 1);**
too many arguments to function 'void mpu_set_accel_bias_6050_reg(const long int*)'

**Comment by brumster** [comment]
Ah looks like the function changed in the Invensense drivers - try removing the second variable (so just leave the aBias parameter; drop the "1"). Search for all calls for mpu_set_accel_bias_6050_reg and change them all, so there's only the first parameter passed. I suspect it will now compile? If so, I'll get the fix uploaded... cheers.

**Comment by privategrim** [comment]
Are you saying to delete "1"?? When I delete 1, it can be uploaded. When I calibrate via EDTracker UI, the two dots keep moving around and can't be centered (tried many clicks on "calculate bias value"). But, after I test on DCS, the drift is drastically reduced.

I think the drift is bearable for me. But soon I will replace my MPU6050 for better result.

In EDTracker UI, I let it stay still for about 15 minutes, and than I click "save drift compensation".

**Comment by brumster** [comment]
Cool, ok, I will update the code to fix the incorrect function calls in the next few days but for now you have fixed it locally yourself.

**Comment by privategrim** [comment]
Ok... Thanks for your assist, appreciate it.

**Comment by brumster** [comment]
Fixed in f50a470 commit
