### ISSUE TITLE
No Gyro defined

### ISSUE THREAD

**Issue by patrickpoirier51** [brumster/EDTracker2#2]
Hello,
I get this error when trying to compile EDTracker2_9250 
arduino-1.6.6/libraries/InvensenseMotionDriver/inv_mpu.c:122:2: error: #error Which gyro are you using? Define MPUxxxx in your compiler options.
 #error  Which gyro are you using? Define MPUxxxx in your compiler options.

Note:
From your last mod, the define MPU9250 has been removed?

Regards

**Comment by patrickpoirier51** [comment]
Made some progress:  added  #define MPU9250 in /avr/cores/arduino/Arduino.h
Now, I get this error: EDTracker2_9250:173: error: 'TrackState_t' does not name a type
 TrackState_t joySt;

**Comment by brumster** [comment]
It's defined in the hardware files, so controlled by the device you choose in your Arduino IDE. It's not needed in the main sketch. Sounds to me like you have old hardware files, or have the wrong device type selected?

**Comment by patrickpoirier51** [comment]
It is working now... Just had to read carefully where to store the hardware files :-( 
I suggest that you add this to the main README:
Place the "edtracker" folder into your <Arduino Install>/hardware/ folder. 
Thanks for your support and this great product

**Comment by brumster** [comment]
No problems; will accept as a doco defect and address soon... ;)
