### ISSUE TITLE
Wireless version

### ISSUE THREAD

**Issue by Pheluc** [brumster/EDTracker2#21]
Could you help me in creating the wireless version. What would be the best device to send and receive data without delay and without losing the quality of HIT device?

I don't know if this would be the right place for this type of questioning. If it is not, you can delete it and please contact us via email pheluc@gmail.com.

**Comment by brumster** [comment]
Sorry, I don't have the time. Designing Wireless Pro was 3 years of my life I won't be getting back so, no offence, but I'll be buggered if I'm going through that fun again 😉 😄  !! Realistically, I'm not sure an opensource wireless version would be entirely practical anyway, given all of the modules/dev boards available out there...
