### ISSUE TITLE
Arduino Leonardo + MPU6050 Usb device not recognized

### ISSUE THREAD

**Issue by Fratee** [brumster/EDTracker2#26]
Hi,

First thanks for you dedication to the project, having moved everything here to make it available to everyone, really appreciated.

Anyway I have a strange issue i couldn't figure out. 
my setup is an Arduino Leonardo + MPU6050. I'm able to load the calibration sketch and calibrate the device.
but when i load the final firmware Windows says "USB device not recognized".
In the device manager i see:
![image](https://user-images.githubusercontent.com/43710005/105773435-2bbb5e00-5f64-11eb-9684-60c75e92dc48.png)

I tried to lower the DEFAULT_MPU_HZ to 100 as suggested in an older issue but no luck.

Any idea on the issue?
(Also i made it work a couple of years ago with this identical setup, now not working anymore...)

Elia

**Comment by brumster** [comment]
Hi Elia,

Windows drivers? Maybe try USBDeview tool to investigate what drivers are recognised when the device is plugged it; it can also be used to remove the device entries from the registry and clean up your PC.

Try a different cable too just to be safe, and a different port in case it's a power issue or USB3 driver related.

**Comment by Fratee** [comment]
Thanks for your reply.

Here USB deview infos:
![image](https://user-images.githubusercontent.com/43710005/105838346-46c3b780-5fd0-11eb-9ad9-800b5426f420.png)

Changing usb port to 2.0 and also cable did not work.

By "cleaning" do you mean removing the reg entry?
![image](https://user-images.githubusercontent.com/43710005/105838625-9efab980-5fd0-11eb-902b-268f1e544878.png)

The thing is that the calibrate sketch is working, do you know changes between the two (dev HID maybe?) ?

Elia

**Comment by Fratee** [comment]
Good news, managed to fix.

Here are the changes i made to `EDTracker2_6050.ino` :
added delay after serial begin
```
Serial.begin(115200);
delay(500);
```

commented:
`//TWBR = 12; // 12 400kHz I2C clock (200kHz if CPU is 8MHz)`

changed port from D to C:
```
  // Disable internal I2C pull-ups
  cbi(PORTC, 4);
  cbi(PORTC, 5);
```

Again this is now working with Arduino Leonardo with the MEGA32U4 and MPU8060:

Here my edited file:
[EDTracker2_6050.ino.txt](https://github.com/brumster/EDTracker2/files/5873164/EDTracker2_6050.ino.txt)

You may consider changing these also in the repo, so it reflects the calibrate settings. Maybe? dunno

Thanks for your support @brumster , you got me thinking a little 😉 
(you can mark as closed if you are satisfied)

Elia

**Comment by brumster** [comment]
Ah good spot on the i2c pullups; I will do some sanity checking between the two sketches and update accordingly! I'll keep open for now just to ensure I don't forget, as I might not get round to it until the weekend ;)

**Comment by brumster** [comment]
Fixed in 2.21.1

**Comment by andywong1026** [comment]
Very  good. Please post the firmware file in .hex format so I could flash with xloader.

**Comment by brumster** [comment]
Done - now available in the firmwares folder

**Comment by andywong1026** [comment]
Thank you!
