### ISSUE TITLE
Can I use the MPU-92/65?

### ISSUE THREAD

**Issue by beerbug** [brumster/EDTracker2#35]
When i tried to make the EDTracker2 with MPU-92/65, the EDTrackerUI doesn't work.
I can't calibration the EDTracker2 with the EDTrackerUI .
The serial monitor shows an "Mag oops [7]" error.
Can I use the MPU-92/65?

**Comment by brumster** [comment]
Hi

There is no such thing _technically_ as an MPU-92/65 but some boards are marked up that way from China.

See other issue #5 ; will mark this as duplicate
