### ISSUE TITLE
EDTRacker GUI does not recognize Arduino board (CH340 UART driver)

### ISSUE THREAD

**Issue by padcom** [brumster/EDTracker2#4]
EDTRacker GUI does not recognize Arduino board (CH340 UART driver). This means that using the cheaper clones of Arduino is not possible. Can you fix it?

**Comment by brumster** [comment]
EDTracker is designed for Atmel MEGA32U4 devices only, because of how they implement direct USB drivers on-chip. You don't state what Arduino you're using but I presume it's a Pro Mini or something - it's not compatible with these devices. Please confirm and I will close.

**Comment by brumster** [comment]
Question answered. Feature request will not be implemented due to hardware limitations.
